Giannis Liakos presentation
devstaff-crete/meetup43-Microservices pull request #1
Opened 2019-04-08 15:04 UTC by jliakos

Giannis Liakos presentation

2019-04-08 15:07 UTC, gsaslis approved these changes

2019-04-08 15:09 UTC, gsaslis requested changes
actually... @jliakos would you mind renaming the file with the title of your talk + your name ?

it will make it easier for folks to find your talk ;)

2019-04-09 07:14 UTC, jliakos commented
Renamed

2019-04-09 15:47 UTC, gsaslis approved these changes

2019-04-09 15:47 UTC, gsaslis commented
ok - assuming you didn't want your name on the file, so approving + merging ;) 

Thanks!!

2019-04-09 15:47 UTC, merged